### PR TITLE
Expanding UI base

### PR DESCRIPTION
**Pull request by Minecraftian14**
Did big changes again...
Well don't hate me 😁

As for now, CircularText is redundant, so I seek your permission to remove it.

### CODE REVIEW

**Comment by JasonTheKitten** [comment]
The ComponentUI-esque code should not be part of the Component itself. This will likely create problems when we do things such as add printer support in the far future.

One thing I was thinking about doing is to be able to specify the Appearence and Layout directly within the UI manager. I have not yet decided whether I will go through with this decision.

**Comment by JasonTheKitten** [comment]
Also, I'm good with adding the text argument to the constructor, but I still wish to retain the getter and setter.

**Comment by Minecraftian14** [comment]
I totally agree that I have gone against your current design.
It was more or less like a prototype-idea for customisable appearance.

As you can see, TextButton is a specialised component for 
* Having two levels of complexity or graphic layers for UI drawing.
   - As such, they rely on only a binary property (background color and forground color)
   - It can be expanded to have a **Palette** for each layer.
   - Each palette by defaults yields the first color, that will be the default color for drawing.
   - Then one can simply provide/change a **PaletteGroup** which will completely change the color scheme of the application.
* Currently, there are two Appearance objects for TextButton, one is user defined which controls the background drawing. The other one is it's internal Appearance which first uses the user defined Appearance and then paints the text.
* Ideally, if you agree on this change, or maybe split the class purposes more, the following changes are pending
   - Creating an abstract appearance implementation which manages external/user defined appearance by itself. Thus we only need to extend it and render the text, further decreasing repeating code.
   
Other advantages
* With this the actual drawing of the UI and the controlling over the component's drawing is now separated. Which also allows a user (who would probably want to use 🎀) to easily provide a "reusable" and "primary" implementation of Appearance.
* Controlling overall color scheme to feel different flavours and prototyping it will become very easy. For other applications which also allow changing colors via a settings menu, it will become much easier. (and a single repaint can change the look, no need for a restart)

**Comment by JasonTheKitten** [comment]
I'll look into this more later. We should probably change the architecture some, but Components should not have a specific UI - in the future, it should be possible to change which component UI is in effect without affecting the actual component at all (except, of course, binding and unbinding the UI).
I plan to eventually scrap the ComponentUI altogether and instead just rely on the layout and appearance.
We should probably have a better pipeline for communicating user preferences with the appearance. We already have a way to hot-reload which UIManager we are using (RibbonSkijaWindow#bind), but we should have a better way to communicate preferences like color.

**Pull request closed without merging**
